export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_MOVIES_BY_QUERY = 'FETCH_MOVIES_BY_QUERY';

export const FAVOURITES = 'FAVOURITES';
export const DELETEFAV = 'DELETEFAV';

// export const ADD_LOCALSTORE = 'ADD_TO_STORAGE';